/******************************************************************************************************
 * Version          Date             Name           Description
 * =====================================================================================================
 * v1.1            09/16/2024       Add Method      A new method(add) method is being added to this class
 * 
 * 
 ********************************************************************************************************/


public with sharing class TestclassforGithub {

   public static Integer add(Integer a, Integer b){
      return a + b;
   }
   public static Integer sub(Integer a, Integer b){
      return a - b;
   }

}
